import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  root: { flex: 1, backgroundColor: "#F3F4F8" },
  mt18: { marginTop: 18 },

  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  menuButton: { padding: 4 },
  topBarCenter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    justifyContent: "center",
  },
  topBarTitle: { fontSize: 15, fontWeight: "600", color: "#1F2937" },

  scrollContent: { paddingHorizontal: 16, paddingTop: 20 },

  pageTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 4,
  },
  pageSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 22,
    lineHeight: 20,
  },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },

  fieldLabel: {
    fontSize: 13.5,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  required: { color: "#EF4444" },

  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
  },
  input: {
    flex: 1,
    paddingVertical: Platform.OS === "ios" ? 13 : 10,
    fontSize: 14.5,
    color: "#111827",
  },
  dropdownChevron: { marginLeft: 6 },

  textAreaWrapper: { alignItems: "flex-start", paddingTop: 4, minHeight: 100 },
  textArea: { minHeight: 88, paddingTop: 10 },

  uploadCard: {
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 18,
    paddingHorizontal: 14,
    alignItems: "center",
    backgroundColor: "#FAFBFF",
  },
  uploadIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  uploadHint: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 14,
  },
  uploadActions: { flexDirection: "row", gap: 10, width: "100%" },
  uploadPrimaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#6366F1",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  uploadPrimaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "600" },
  uploadSecondaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  uploadSecondaryText: { color: "#374151", fontSize: 14, fontWeight: "600" },

  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#6366F1",
    borderRadius: 12,
    paddingVertical: 15,
    marginTop: 18,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    backgroundColor: "#A5B4FC",
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: { color: "#FFFFFF", fontSize: 15.5, fontWeight: "700" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#9CA3AF",
    paddingHorizontal: 14,
    paddingVertical: 8,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 10,
    marginHorizontal: 4,
  },
  modalItemActive: { backgroundColor: "#EEF2FF" },
  modalItemLabel: { fontSize: 15, color: "#374151", fontWeight: "500" },
  modalItemLabelActive: { color: "#6366F1", fontWeight: "700" },
});
